---
version: 2
updates:

  # Update `GitHub Action` dependencies weekly.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]
    auto-merge: true

  # Update pip dependencies weekly.
  - package-ecosystem: pip
    directory: /inventory
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "python"]
    auto-merge: true

