---
AWSTemplateFormatVersion: 2010-09-09
Description: A collection of resources used to manage the jcleal.me website.

Parameters:
  Repository:
    Description: The repository this stack is deployed from.
    Type: String

  HostedZoneId:
    Description: The id for the domain registered via AWS Route53.
    Type: String

  Domain:
    Description: The domain registered.
    Type: String

  AcmCertificateArn:
    Description: The certificate verifying the given domain.
    Type: String

Conditions:
  CreateResources: !Equals [ !Ref "AWS::Region" , "ap-southeast-2" ]

Resources:
  Website:
    Type: AWS::S3::Bucket
    Condition: CreateResources
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref Domain
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      Tags:
        - Key: repository
          Value: !Ref Repository

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateResources
    Properties:
      Bucket: !Ref Website
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${Website}/*

  DistributionLogBucket:
    Type: AWS::S3::Bucket
    Condition: CreateResources
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: repository
          Value: !Ref Repository

  DistributionLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateResources
    Properties:
      Bucket: !Ref DistributionLogBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudFrontAccessLogs
            Principal:
              AWS: !Ref "AWS::AccountId"
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetBucketAcl
              - s3:PutBucketAcl
            Resource:
              - !Sub 'arn:aws:s3:::${DistributionLogBucket}'
              - !Sub 'arn:aws:s3:::${DistributionLogBucket}/*'

  Distribution:
    Type: AWS::CloudFront::Distribution
    Condition: CreateResources
    DependsOn:
      - Website
      - DistributionLogBucket
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Ref Website
        Origins:
          - Id: S3Origin
            DomainName:
              Fn::Join:
                - ''
                - - !Ref Website
                  - !Sub .s3-website-${AWS::Region}.amazonaws.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        HttpVersion: http2
        Aliases:
          - !Ref Website
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
        Logging:
          Bucket: !Sub "${DistributionLogBucket}.s3.amazonaws.com"
          Prefix: !Ref Website
          IncludeCookies: false
      Tags:
        - Key: repository
          Value: !Ref Repository

  WebsiteRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Condition: CreateResources
    DependsOn:
      - Distribution
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref Domain
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_endpoints
            DNSName: !GetAtt Distribution.DomainName

Outputs:
  Bucket:
    Description: The S3 bucket used to host the website.
    Value: !Ref Website
