---
name: Generate README
on:
  workflow_call:
    inputs:
      org:
        description: The GitHub organisation owning the repository.
        type: string
        default: jmpa-io
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      AWS_RUNNER_ROLE_NAME:
        required: true
      ADMIN_GITHUB_TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Checkout templates.
        uses: actions/checkout@v4
        with:
          repository: jmpa-io/templates
          path: .templates
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Configure AWS.
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_RUNNER_ROLE_NAME }}
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate README.
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        run: bash .templates/bin/README.sh ${{ inputs.org }}

      - name: Commit & push README.
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "docs: update README.md [skip ci]"
          git push
